spring:
  application:
    name: wtong.eurekaserver
    admin:
      enabled: true
  http:
    encoding:
      charset: UTF-8
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
